apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  namespace: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: neoooo2/yolo-backend:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://app-mongo:27017/ecommerce"
        - name: PORT
          value: "5000"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
