apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-mongo
  namespace: yolo
spec:
  serviceName: "yolo-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: yolo-mongo
  template:
    metadata:
      labels:
        app: yolo-mongo
    spec:
      containers:
      - name: mongo
        image: bitnami/mongodb:7.0
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /bitnami/mongodb
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
