apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo
  namespace: yolo
spec:
  selector:
    app: yolo-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  publishNotReadyAddresses: false
