apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  selector:
    app: yolo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
