apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  namespace: yolo
  labels:
    app: yolo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
      - name: frontend
        image: neoooo2/geoffrey-yolo-client:v1.0.0
        ports:
        - containerPort: 80
